spring.application.name=publicapi

spring.output.ansi.enabled=always

logging.level.root=info

# OpenAPI 관련 서버 정보
# 개발자가 추가 생성한 설정 정보
redtable.service-key=vxLvUXF7nABWKmCBXM3j6gjSz5ZDbwSI96wxMfKM7sNfqj8qkpQD8QY8c2g4hqXi
redtable.base-url=https://busan-food.openapi.redtable.global